name: Robot Framework CI

on:
  push:
    branches:
      - main
      - feature/ci-pipeline

  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Installer Robot Framework
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary

      - name: Installer Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Vérifier Chrome
        run: |
          google-chrome --version

      - name: Lancer les tests Robot
        run: |
          robot -d ResultCI ./Tests/Seleni/Form.robot

      - name: Analyser les résultats avec AI Agent
        if: always()
        run: |
          python Ai_agent/Analyze_robot_results.py

      - name: Préparer le rapport pour GitHub Pages
        if: always()
        run: |
          mkdir -p public
          cp -r ResultCI/* public/

      - name: Déployer les rapports sur GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public